### PR TITLE
make Fortran init of A agree with C - somehow doesn't affect correctness

### PR DESCRIPTION
**Pull request by jeffhammond**
@rfvander Can you explain to me why changing the initialization of A does not impact the correctness of stencil?

### CODE REVIEW

**Comment by rfvander** [comment]
The initialization sets the filed variable A(x,y) equal to cx*x+cy*y, Taking the divergence of this field gives cx+cy uniformly across the domain. Adding a constant to each of x and y (the index shift you mentioned comes down to that) does not alter the value of the divergence.

**Comment by rfvander** [comment]
Github removed some symbols from my comment. cxx + cyy should be cx \times x + cy \times y.

**Comment by jeffhammond** [comment]
@rfvander That's because `*` is Github markup for italic (or bold if you use two).  I edited your post to add tildes, which create a literal expression, similar to LaTeX's `\texttt{}`.

*italic* is `*italic*`
**bold** is `**bold**`
***bold italic*** is `***bold italic***`

**Comment by rfvander** [comment]
*S*p**len**d***id***!

**Pull request merged**
