### PR TITLE
Multidimensional arrays in C99

### PR DESCRIPTION
**Pull request by jeffhammond**
Do not merge this until reactivating all Travis tests and pushing...

### CODE REVIEW

**Comment by jeffhammond** [comment]
@rfvander We've been discussing this for a while now.  Are you okay if this is merged?

**Comment by rfvander** [comment]
I am concerned that the casts of 32b integers to 64b wherever they occur make the codes less readable.
I am also concerned that the removal of the macro for the weight array in the stencil implementations makes the codes less readable.
It is not clear to me whether radius in the stencil codes is still a compile time variable, as it should be.

**Comment by jeffhammond** [comment]
Radius is defined via `const int radius = RADIUS;`, which makes it a compile-tile constant.

I assume you are concerned about the readability of, e.g., this:
```
            const size_t offset_ij = (size_t)i*(size_t)order+(size_t)j;
            const size_t offset_ji = (size_t)j*(size_t)order+(size_t)i;
            B[offset_ij] += A[offset_ji];
            A[offset_ji] += 1.0;
```

That code only exists because I wasn't sure if we could go all-in with C99 or not.  I will be very happy to delete it and use only the real C99 code below.
```
    for (int it=0; it<order; it+=tile_size) {
      for (int jt=0; jt<order; jt+=tile_size) {
        for (int i=it; i<MIN(order,it+tile_size); i++) {
          for (int j=jt; j<MIN(order,jt+tile_size); j++) {
            B[i][j] += A[j][i];
            A[j][i] += 1.0;
          }
        }
      }
    }
```

As for whether `const size_t offset_ij = (size_t)i*(size_t)order+(size_t)j;` reduces readability versus doing it in a macro, I have a strong personal preferences towards never use macros in the manner you do, because the require nonlocal information to parse the code, whereas doing the cast explicitly at the innermost scope ensures that any C programmer can look at those four lines of code and nothing else and know exactly what is going on.

**Comment by rfvander** [comment]
This code snippet is indeed not well readable and confusing (not pedagogical). Unless the reader has done extensive experiments with particular compilers, it will not be clear why promoting 32b integers inside a loop body is better than declaring the loop indices 64b from the start. To me it is counterintuitive and produces clutter.
If macros are well-organized—all in the same location in the file, sensible and intuitive names and definitions—I find very little to recommend against them, though I agree with a comment made earlier by Intel’s Jim Dinan that macros should expose all the variables used inside. Anybody who can type “ctrl-x 2” in Emacs, or equivalent in other editors, can keep a window open on the definitions of relevant macros as a memory reference. Keeping actual code terse and clear promotes understanding of the overall program.
The full-blown C99 style solves the problem of cluttering of some loop bodies with integer promotions, but others remain (verification). The uniform and simplest approach is to declare all integers appearing in constructs that may suffer integer overflow as 64b. It would be good to characterize the performance deficit caused by its adoption.

**Comment by jeffhammond** [comment]
> This code snippet is indeed not well readable and confusing (not pedagogical). Unless the reader has done extensive experiments with particular compilers, it will not be clear why promoting 32b integers inside a loop body is better than declaring the loop indices 64b from the start. To me it is counterintuitive and produces clutter.

I talked to John Pennycook about this, and there are both hardware and software reasons to use 32b loop indices.  I'll perform the experiments and let you know the results.

Remember also that IL32P64 platforms exist (Windows is the most popular example), so we can't just use `long`.  We need to use `long long`, `size_t`, `ptrdiff_t`, etc. but this leads to various unpleasantness (some mitigated by requiring C99).

> If macros are well-organized—all in the same location in the file, sensible and intuitive names and definitions—I find very little to recommend against them, though I agree with a comment made earlier by Intel’s Jim Dinan that macros should expose all the variables used inside. Anybody who can type “ctrl-x 2” in Emacs, or equivalent in other editors, can keep a window open on the definitions of relevant macros as a memory reference. Keeping actual code terse and clear promotes understanding of the overall program.

We are very much in the regime of personal preference, along the lines of Vim vs Emacs or C vs Fortran.  I prefer the explicit indexing scheme even up to 6-dimensional arrays (https://github.com/jeffhammond/nwchem-tce-triples-kernels/blob/master/src/ccsd_t_kernels_f2c.c) because it is easier for me to understand code with zero levels of indirection.

> The full-blown C99 style solves the problem of cluttering of some loop bodies with integer promotions, but others remain (verification). The uniform and simplest approach is to declare all integers appearing in constructs that may suffer integer overflow as 64b. It would be good to characterize the performance deficit caused by its adoption.

There is very little possibility for overflow in the C99 VLA solution, because overflowing a 32b index for _one_ loop requires exabytes of memory for the square problems and many gigabytes even if one runs the very silly case of `Synch_p2p` with a 2x2147483649 grid.

If we really want to be safe, we should just eliminate array notation and move to direct pointer arithmetic, since `a++` can't overflow.

**Comment by rfvander** [comment]
Thanks, I will await these performance experiments.
My comment about integer overflow remaining a problem in verification tests refer to the fact that in the case of Transpose and Synch_p2p the analytical values of array elements are integer expressions. These overflow in a similar manner as linearized indices, unless sub-expressions are carefully cast to doubles or 64b integers.

**Comment by jeffhammond** [comment]
Indeed, for both 1D and 2D indexing, much explicit casting is required for the verification tests to be overflow-safe...
```c
static inline double prk_transpose_check(int order, int iterations,
#if PRK_TRANSPOSE_1D_ARRAY
                                         double * const restrict B)
#else
                                         double (* const restrict B)[order])
#endif
{
  double abserr = 0.0;
  const double addit = ((double)(iterations+1) * (double) (iterations))/2.0;
  for (int j=0;j<order;j++) {
    for (int i=0;i<order; i++) {
      const size_t offset_ij = (size_t)i*(size_t)order+(size_t)j;
#if PRK_TRANSPOSE_1D_ARRAY
      const size_t offset_ji = (size_t)j*(size_t)order+(size_t)i;
      abserr += fabs(B[offset_ji] - ((double)offset_ij*(iterations+1.)+addit));
#else
      abserr += fabs(B[j][i] - ((double)offset_ij*(iterations+1.)+addit));
#endif
    }
  }
  return abserr;
}
```

**Comment by rfvander** [comment]
And I think I am responsible for a lot of those casts…
Would be nice to be able to chuck them.

**Comment by jeffhammond** [comment]
Since performance does not matter in the verification code, that is one place where can just be lazy and use 64b indices, which will eliminate all but one cast (64b integer to 64b float), although I guess we can make that one implicit.

**Comment by rfvander** [comment]
That is a good point! We want the verification to be scalable and not pathologically slow, but otherwise we do not care.

**Comment by jeffhammond** [comment]
Same for initialization.  Since `order` needs to be 32b for the timed loops to avoid 32b vs 64b comparison (the compiler will not like this at all), I will create `order64` on the fly for init and verification, but otherwise the code should be free of integer casting.

**Comment by rfvander** [comment]
Here are some performance numbers for the current (perf_orig) version of SERIAL/Transpose, which uses longs for the loop indices and order, as well as for the proposed version (perf_new) that uses ints for these quantities and casts them to longs in the bodies of the hot loops.
[rfvander@esgmonster Transpose]$ grep Rate perf_*
perf_new:Rate (MB/s): 3239.401736 Avg time (s): 7.902694
perf_new:Rate (MB/s): 3268.043184 Avg time (s): 7.833434
perf_orig:Rate (MB/s): 3478.376707 Avg time (s): 7.359755
perf_orig:Rate (MB/s): 3497.223800 Avg time (s): 7.320092
The runs were done using matrices of order 40,000 with a tile size of 32. In each case I used 5 iterations. This was done on ESGmonster. This is obviously not a conclusive parameter sweep, but I do not see a reason to do the casts.

Rob

**Comment by jeffhammond** [comment]
Let's compare 1D long impl vs C99 version with int. There's no cast in C99 VLA impl. 

Big matrix is more BW limited. Should see bugger effect of inner loop with 100+ iterations with matrix that fits in L3. 

I'm also curious how Atom arch does with 64b loop indices...

I'll run all of these tonight.

**Comment by rfvander** [comment]
That is fine. In the spirit of providing GOOD--but not ninja--reference implementations, if the result is a wash or only slightly in favor of casts, I don't want to go that route. A person looking at the code should understand immediately why certain decisions were made. That is the pedagogical function of the PRK.

**Comment by jeffhammond** [comment]
I'm just going to keep your C89 code and add a new C99 directory. People can choose which one they want to use. We have wasted far too much time on this religious debate. We have better things to do.

**Comment by rfvander** [comment]
Very good. But I really do not agree with your proposed structuring of the repo. You cannot put C89 and MPI1 at the same level, because an MPI implementation can use C89, C99, Fortran77, Fortran90m etc. Now that we have multiple languages and language variants, as well as some non-library-based parallelization approaches that are inherent properties of languages (Chapel, Charm++), it is less clear what the subdivisions should be. I propose this one:
Where there is a choice of languages (X,Y,Z) to implement a certain kernel using parallelization strategy P, put it in directory P-X, P-Y, P-Z, or swap P and language. SERIAL is a parallelization strategy. Where there is no choice of language, leave off its identifier. This reflects best the spirit of the PARALLEL Research Kernels and keep the hierarchy flat. Transposing the matrix {Parallelization-Strategy,kernel} can be considered.

**Comment by rfvander** [comment]
That last sentence should be:
Transposing the matrix {ParallelizationStrategy-Language,kernel} can be considered.

From: Van Der Wijngaart, Rob F
Sent: Tuesday, February 23, 2016 10:37 AM
To: 'ParRes/Kernels'; ParRes/Kernels
Subject: RE: [Kernels] Multidimensional arrays in C99 (#67)

Very good. But I really do not agree with your proposed structuring of the repo. You cannot put C89 and MPI1 at the same level, because an MPI implementation can use C89, C99, Fortran77, Fortran90m etc. Now that we have multiple languages and language variants, as well as some non-library-based parallelization approaches that are inherent properties of languages (Chapel, Charm++), it is less clear what the subdivisions should be. I propose this one:
Where there is a choice of languages (X,Y,Z) to implement a certain kernel using parallelization strategy P, put it in directory P-X, P-Y, P-Z, or swap P and language. SERIAL is a parallelization strategy. Where there is no choice of language, leave off its identifier. This reflects best the spirit of the PARALLEL Research Kernels and keep the hierarchy flat. Transposing the matrix {Parallelization-Strategy,kernel} can be considered.

**Comment by jeffhammond** [comment]
Of course I agree with you regarding directory hierarchy, ie MPI and C99 are not peers.  I just cannot implement every change at once :-)

**Comment by jeffhammond** [comment]
My preference is `$(LANGUAGE)/$(KERNEL)-$(PARALLELISM).$SUFFIX` or  `$(LANGUAGE)/$(PARALLELISM)/$(KERNEL).$SUFFIX`, although I started using the former with Fortran already.

**Comment by jeffhammond** [comment]
I am going to close this.  The directory reorganization is unnecessary thrash.  I started over with modern C in `C1z`, which is based on the C++11 ports.  It is trivial to reimplement VLAs there.

**Pull request closed without merging**
