### PR TITLE
add Chapel from upstream

### PR DESCRIPTION
**Pull request by jeffhammond**
Code take directly from https://github.com/chapel-lang/chapel/tree/08f3e9c8414d0aeedaa9ad8667edc556c0cb86e8/test/studies/prk

Authorship, according to the source file comments:

dgemm-summa.chpl:       Contributed by Rahul Ghangas (ANU)
dgemm.chpl:             Contributed by Engin Kayraklioglu (GWU)
nstream.chpl:           Contributed by Engin Kayraklioglu (GWU)
pic.chpl:               Contributed by Engin Kayraklioglu (GWU)
sparse.chpl:            Contributed by Engin Kayraklioglu (GWU)
stencil-serial.chpl:    Contributed by Ben Albrecht, Ben Harshbarger (Cray Inc.)
stencil.chpl:           Contributed by Ben Albrecht, Ben Harshbarger (Cray Inc.),
p2p-serial-fast.chpl:   Contributed by Ben Albrecht (Cray Inc.)
transpose-serial.chpl:  Contributed by Ben Albrecht (Cray Inc.)
transpose.chpl:         Contributed by Ben Albrecht (Cray Inc.),

Additional contributions may have been made by authors, which can be deduced from the git history of the Chapel project.

LICENSE and COPYRIGHT have been copied from the Chapel project, to be safe.  The Chapel LICENSE file was modified to remove irrelevant comments about the third-party dependencies of Chapel, which are, of course, not part of the Chapel test source code contained in this commit.

If this pull request is fixing a bug, please link the associated issue.
The rest of this template does not apply.

If this pull request is providing a new implementation of the PRKs,
please use the following template.

Note that checking all of the boxes is not required.

### Which kernels are implemented?

- [x] synch_p2p (p2p)
- [x] stencil
- [x] transpose
- [x] nstream
- [x] dgemm
- [ ] reduce
- [x] sparse
- [ ] branch
- [ ] random
- [ ] refcount
- [ ] synch_global
- [x] PIC
- [ ] AMR

### Documentation and build examples

If your implementation uses a new programming model that is not
ubiquitious (i.e. included in the system compiler on most systems)
then you need to provide a link to the appropriate documentation
for a new user to install it, etc.

We strongly recommend that you add the appropriate features
to `make.defs.${toolchain}` if appropriate.

### Do you certify that your contribution is made in good faith and does not attempt to introduce any negative behavior into this project?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by jeffhammond** [comment]
@bradcray if you have time to look, I'd appreciate at least one person from the Chapel project signing off on this, to make sure the copyright/license treatment is appropriate.  The source code is unmodified.

**Comment by bradcray** [comment]
Hi @jeffhammond  —

We're wrapping up the freeze for our release today, so here are some quick reactions, in approximate order that they occurred:

* Oh wow, PRK is still going?!? 😮 
* Oh nice, Jeff still thinks about Chapel!  😍 
* This is open-source, so we can't really stop you.  😅 
* These benchmarks haven't really received much attention since 2016 apart from keeping them working.  🙁 
* Even then, I'm not sure how much performance-tuning attention they received at that time.  😓 
* I wonder how they could be improved using newer Chapel features?  🤔 

Less jokingly:  Generally, I'm supportive of the merge.  A little nervous about keeping them working over time without ongoing testing (or does your CI/CD help with that?  I can't recall).  The fact that we're past Chapel 2.0 should make this much better now than it was for most of the time since 2016, but I see that I changed one of them just over a month ago (b/c it relied on features not stabilized in Chapel 2.0), so other adjustments seem likely to be required.

I'm mostly nervous about people treating these as the gold standard for Chapel and drawing conclusions from them as a result, so would be curious whether you'd consider adding a disclaimer like the following to the very top of the README:

> This directory’s contents were created as a copy of https://github.com/chapel-lang/chapel/tree/08f3e9c8414d0aeedaa9ad8667edc556c0cb86e8/test/studies/prk and the ongoing maintained versions of them as Chapel evolves can be found in https://github.com/chapel-lang/chapel/tree/main/test/studies/prk.  Note that these versions have not necessarily been studied in great depth w.r.t. performance nor considered in light of Chapel features that have been added since they were originally written circa 2016 (e.g., `foreach` loops supporting vectorization; GPU support).  As a result, please take any performance obtained from them with a grain of salt and consider contacting the Chapel team if you have any questions, find any surprises, or are planning to publish conclusions based on their results (https://chapel-lang.org/community/).

To your specific questions, with the caveat that I'm not a lawyer:
* Copyright looks fine to me
* Rather than using an edited copy of LICENSE, I'd suggest copying our LICENSE.chapel file into this directory and renaming it to LICENSE for simplicity and to avoid questions like "where's the LICENSE.chapel file that's mentioned?" and "what is the second category?" (it should just be the Apache 2.0 license text, unmodified)

Only vaguely related: My question about CI/CD reminds me of a conversation that I'm pretty sure you and I had strolling along some California coastal road (Santa Barbara?) about ease of installing Chapel via conventional means (e.g., `apt get chapel`), which makes me want to mention that we now support a Spack package and several Linux packages if you hadn't seen that (https://chapel-lang.org/download/).  I think the Jeff of then would've been very happy at this turn of events (the Brad of then was concerned about potential hits to performance vs. building from source, which remains a concern for the Linux packages, but I'm trying to suppress those.  😅 )

**Comment by jeffhammond** [comment]
> * Oh wow, PRK is still going?!? 😮

Yes, absolutely.

Less than a year ago, I added the first Ada implementations (I hate-learned Ada because somebody in the Fortran standards committee thinks it's great...and that's all I have to say about that) and there is evolution in other parts of the project when people have time.

Julia got some polish recently, for example, and CUDASTF support was added within a week of its launch (SC Best Paper nominee, if you didn't see it).

> * Oh nice, Jeff still thinks about Chapel!  😍

Yes, I was thinking about it again since there are these distributed-memory Python things happening and I think Chapel is a reasonable comparison point if one wants to think that way.

> * This is open-source, so we can't really stop you.  😅

"What is permissible is not always honorable." - Marcus Tullius Cicero

> * These benchmarks haven't really received much attention since 2016 apart from keeping them working. 🙁

This applies to a great deal of the PRK project.

> * Even then, I'm not sure how much performance-tuning attention they received at that time.  😓

This applies to a great deal of the PRK project.

I am very explicit in my public presentations that only nstream and dgemm using a library call deliver absolute performance without tuning.  We know that stencil is optimal nowhere.

> * I wonder how they could be improved using newer Chapel features?  🤔

I am not prepared to answer that one.

> Less jokingly: Generally, I'm supportive of the merge. A little nervous about keeping them working over time without ongoing testing (or does your CI/CD help with that? I can't recall). The fact that we're past Chapel 2.0 should make this much better now than it was for most of the time since 2016, but I see that I changed one of them just over a month ago (b/c it relied on features not stabilized in Chapel 2.0), so other adjustments seem likely to be required.

Automated CI stopped when Travis CI ceased to have a free option.  I have not had time to fully enable GitHub CI, but since you have raised this, I suppose I will put it on the agenda.

> I'm mostly nervous about people treating these as the gold standard for Chapel and drawing conclusions from them as a result, so would be curious whether you'd consider adding a disclaimer like the following to the very top of the README:

First, despite my many efforts to convince people of its utility, virtually nobody uses the PRK project for anything, so the risk of this is very low.

Second, if anyone does use the PRK project because of my outreach efforts, they will have heard me say the above about its lack of suitability for absolute performance measurements.

In any case, I will measure the performance and let you know how things stack up versus relevant comparisons like Julia and Numpy, both of which are doing as well as they should versus C++ and Fortran.

> > This directory’s contents were created as a copy of https://github.com/chapel-lang/chapel/tree/08f3e9c8414d0aeedaa9ad8667edc556c0cb86e8/test/studies/prk and the ongoing maintained versions of them as Chapel evolves can be found in https://github.com/chapel-lang/chapel/tree/main/test/studies/prk.  Note that these versions have not necessarily been studied in great depth w.r.t. performance nor considered in light of Chapel features that have been added since they were originally written circa 2016 (e.g., `foreach` loops supporting vectorization; GPU support).  As a result, please take any performance obtained from them with a grain of salt and consider contacting the Chapel team if you have any questions, find any surprises, or are planning to publish conclusions based on their results (https://chapel-lang.org/community/).

Sure, I will add this now.

> To your specific questions, with the caveat that I'm not a lawyer:
> 
> * Copyright looks fine to me
> * Rather than using an edited copy of LICENSE, I'd suggest copying our LICENSE.chapel file into this directory and renaming it to LICENSE for simplicity and to avoid questions like "where's the LICENSE.chapel file that's mentioned?" and "what is the second category?" (it should just be the Apache 2.0 license text, unmodified)

Thanks.  That makes sense.

> Only vaguely related: My question about CI/CD reminds me of a conversation that I'm pretty sure you and I had strolling along some California coastal road (Santa Barbara?) about ease of installing Chapel via conventional means (e.g., `apt get chapel`), which makes me want to mention that we now support a Spack package and several Linux packages if you hadn't seen that (https://chapel-lang.org/download/). I think the Jeff of then would've been very happy at this turn of events (the Brad of then was concerned about potential hits to performance vs. building from source, which remains a concern for the Linux packages, but I'm trying to suppress those. 😅 )

I will use Spack next time I install Chapel.  Thanks for the tip.

On a related note, I started working on the NWChem Spack package this year because I determined it was easier to do that than to write the documentation for how to build GPU support correctly, particularly since nobody reads our documentation anyways.

**Comment by bradcray** [comment]
Thanks for the responses and reassurances, all of which are helpful!  I would definitely be curious about the performance comparison, but please don't consider it a precondition to merging (or at all).

> I was thinking about it again since there are these distributed-memory Python things happening and I think Chapel is a reasonable comparison point if one wants to think that way.

Makes sense, and thanks!  In that vein, if you haven't come across it, I should also mention Arkouda, which is a Python library supporting interactive HPC from your laptop using a client-server model, where the server side is powered by Chapel (originally developed by Mike Merrill and Bill Reus, but being carried forward by our team along with others):  https://arkouda-www.github.io/

> On a related note, I started working on the NWChem Spack package this year because I determined it was easier to do that than to write the documentation for how to build GPU support correctly, particularly since nobody reads our documentation anyways.

:D

**Review by bradcray — APPROVED** [review]
Looks good to me from a Chapel perspective Jeff, and thanks for bringing us into the loop on this PR!

**Comment by bradcray** [comment]
Oh, and I meant to say:

> First, despite my many efforts to convince people of its utility, virtually nobody uses the PRK project for anything, so the risk of this is very low.

I spent a year or two trying to help fly the PRK flag and get more people interested in it, and am similarly disappointed that that didn't lead anywhere.  I thought (and continue to think) it's a better suite of codes than many the HPC community has come up with.

**Comment by jeffhammond** [comment]
Yeah, I know about Arkouda but haven't had time to look at using it.

> I spent a year or two trying to help fly the PRK flag and get more people interested in it, and am similarly disappointed that that didn't lead anywhere. I thought (and continue to think) it's a better suite of codes than many the HPC community has come up with.

The biggest differentiator from my perspective is that everything else like it is not vigorously curated and actively supported.  While it's only me, it's a better QoS than one can get from HPCC or NPB.

**Pull request merged**
