### PR TITLE
Improvements for Julia

### PR DESCRIPTION
**Pull request by carstenbauer**
@jeffhammond I had a bit of free time and improved/updated the existing Julia kernels a little bit.

I guess the only "controversial" change is using the new (Julia >= 1.11) entry point feature `@main`.

### CODE REVIEW

**Comment by jeffhammond** [comment]
I have no issue depending on the latest version since Julia is OSS and easy to install everywhere.

**Comment by carstenbauer** [comment]
I can also contribute a few dgemm variants. Should I do this here or in a separate PR?

**Comment by jeffhammond** [comment]
You removed precompile _almost_ everywhere.  Should it be removed everywhere?

**Comment by jeffhammond** [comment]
There is a need for `k` as a loop index for timing.  I just made an error in the previous code.  The timer is supposed to start after the 0-th iteration.

**Comment by jeffhammond** [comment]
> I can also contribute a few dgemm variants. Should I do this here or in a separate PR?

Sure.  I started in https://github.com/jeffhammond/PRK/tree/julia-dgemm so I'll push that here and then you can improve upon it.

**Comment by carstenbauer** [comment]
> You removed precompile _almost_ everywhere.  Should it be removed everywhere?

While it's technically valid, it is very untypical/unidiomatic (no one would write these precompile statements). If you really care about precompilation and proper benchmarking, you would probably put things in a package and/or use BenchmarkTools.jl. But, IIUC, performance isn't the primary focus if these benchmarks anyways. (Moreover, the precompile statements are entirely redundant if you want to exclude the first iteration anyways.)

**Comment by carstenbauer** [comment]
I'll remove the remaining precompile statements and reintroduce the first iteration skipping.

**Comment by jeffhammond** [comment]
Performance is really important. I want to measure what every language is capable of. If precompilation helps, I'll use it.

**Comment by carstenbauer** [comment]
> Performance is really important. I want to measure what every language is capable of. If precompilation helps, I'll use it. 

Interesting, because the readme states
> These programs should not be used as benchmarks.

**Comment by jeffhammond** [comment]
That was more or less a stipulation of Intel lawyers from the open-source approval process, many years ago. The PRK should not be used as performance benchmarks for _marketing_ purposes.

**Comment by carstenbauer** [comment]
Alright, there you have a bunch of dgemm variants (for CPU and NVIDIA GPU). I've also undone the `@elapsed` change and ignore the first iteration in the time measurement. Let me know if you need more (for SC) :)

**Comment by carstenbauer** [comment]
Added two CUDA variants for nstream. I'll leave it at that, so, unless you have further comments, this can be merged IMO.

**Review by jeffhammond — CHANGES_REQUESTED** [review]
other than renaming transpose-pretty to transpose-broadcast, which i don't understand and doesn't follow the convention, this LGTM.

**Comment by jeffhammond** [comment]
this doesn't make sense to me.  i think there is a typo in the README (`-e` is missing) but i can only run the command in the interpreter.

```
jhammond@Jeff-M2 JULIA % julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Built by Homebrew (v1.11.1)
|__/                   |

julia> using MPI; MPI.install_mpiexecjl()
[ Info: Installing `mpiexecjl` to `/Users/jhammond/.julia/bin`...
[ Info: Done!
```

```
jhammond@Jeff-M2 JULIA % julia --project -e 'using MPI; MPI.install_mpiexecjl()'
ERROR: ArgumentError: Package MPI [da04e1cc-30fd-572f-bb4f-1f8673147195] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

```
jhammond@Jeff-M2 JULIA % julia --project 'using MPI; MPI.install_mpiexecjl()'
ERROR: SystemError: opening file "/Users/jhammond/Work/PRK/JULIA/using MPI; MPI.install_mpiexecjl()": No such file or directory
```

**Pull request merged**
