### PR TITLE
ISPC

### PR DESCRIPTION
**Pull request by jeffhammond**
Add ports of stencil and transpose for [ISPC](https://ispc.github.io/).  The performance is about half what serial GCC is, but this should be blamed on the programmer until proven otherwise.

### CODE REVIEW

**Comment by jeffhammond** [comment]
This code is not covered by Travis so we merely need to wait to see that these additions don't have any negative side effects (e.g. because stencil code generator was changed).

We should add testing since ISPC is supported by Homebrew and there are binaries online, but this is low priority given the current performance.

**Comment by rfvander** [comment]
I am not familiar with ISPC, so would not be the natural reiewer of this code. However, eyeballing the contents and ignoring "uniform," it looks OK to me.

**Comment by jeffhammond** [comment]
It's a fairly naive port based upon examples on their website.  I'll ask coworkers who developer ISPC for help some day.

**Comment by jeffhammond** [comment]
https://travis-ci.org/ParRes/Kernels/jobs/265427131 is unrelated failure, once again due to Travis and/or Homebrew.

**Pull request merged**
