### PR TITLE
Updates to the mapper code for Stencil

### PR DESCRIPTION
**Pull request by magnatelee**
This pull request contains some updates to catch up the recent changes in the Legion mapper API.

### CODE REVIEW

**Comment by magnatelee** [comment]
Although this change looks like a ninja coding, it is just to make the rest of code work with the new mapping API. The new mapping API is significantly different from the old one and just to catch up that difference ended up taking this amount of changes. There is part that caches the metadata for all processors and memories in the system and this is simply to avoid known inefficiencies in the default mapper implementation. Any Legion programmer who knows the mapping API well and wants to avoid any mapper bottleneck would have written a similar code.

**Comment by magnatelee** [comment]
The other Legion app uses the default mapper, so it should be fine for now, but it might be suboptimal at large node counts. I'll optimize it if I find some time.

**Comment by rfvander** [comment]
OK, sounds good, thank you!

**Comment by jeffhammond** [comment]
@magnatelee Can you cleanup the merge conflict?  It looks trivial but I don't want to break anything.  Once you do that, I'll merge.

**Comment by magnatelee** [comment]
@jeffhammond I just pushed some changes to fix the merge conflict, so I think it's good to go now.

**Comment by jeffhammond** [comment]
Thanks!  I'll merge once Travis is done.

**Comment by jeffhammond** [comment]
Nevermind about Travis.  We do not test Legion code in Travis and these changes cannot break anything else.

**Pull request merged**
