### PR TITLE
Fortran OpenMP target

### PR DESCRIPTION
**Pull request by jeffhammond**
1) move all Fortran stuff to one directory (ala Cxx11)
2) implement Stencil and Transpose with OpenMP `target`
3) incorrectly implement p2p with OpenMP (correct some of the time, so clearly it has a race condition)

@rfvander I would be eternally grateful if you could take a look at 3.

I'm going to merge in spite of 3 because 1 and 2 are important.  We can fix 3 later.

### CODE REVIEW

**Comment by rfvander** [comment]
Eternity is a long time, but I will be happy to review. Stay tuned.

**Comment by rfvander** [comment]
It looks like the intention of the code is to be completely serial at this point, since pretty much all work is carried out inside master regions, except ... the update of the bottom left corner value. All threads do this. It is possible that some threads do this much delayed, such that the master thread races ahead and is on the next iteration, plops in the correct value for the left corner value, after which that value gets clobbered with a stale value from another thread. The master thread then reads and uses that stale value.
If my conjecture is correct, the incidence of errors should go down as you increase the size of the grid,. The fix is to let the master thread to that single-point update as well. Of course, you'd then have an exceedingly boring code.

**Comment by jeffhammond** [comment]
@rfvander It's pretty hard to collect karmic debts from the dead, so I'm estimating `6<log(eternity,2)<7`.

**Comment by jeffhammond** [comment]
@rfvander Did you look at https://github.com/jeffhammond/PRK/blob/fortran-openmp-target/FORTRAN/p2p-openmp.f90?  The key part is:
```fortran
    do j=2,n
      if (me > 1) then
        loop = .true.
        do while (loop)
          !$omp flush
          !$omp atomic read
          copy = flags(prev)
          if ( copy >= (j-1)*(k+1) ) loop = .false.
        enddo
      endif
      do i=2,m
        grid(i,j) = grid(i-1,j) + grid(i,j-1) - grid(i-1,j-1)
      enddo
      if (me < nt) then
        !$omp flush
        !$omp atomic update
        flags(me) = flags(me) + 1
      endif
    enddo
```

**Comment by jeffhammond** [comment]
Oh junk.  I didn't change the loop bounds in the middle part.  Sorry about the noise.  I will fix this.

**Comment by rfvander** [comment]
And I obviously didn't look at the version you wanted me to look at .... I checked out FORTRAN/Synch_p2p/p2p.f90

**Pull request merged**
