### PR TITLE
Fix bug due to unevenly divisible size

### LINKED ISSUE #97: Fortran coarray Stencil incorrect (sometimes)
Correctness depends on the problem size...
# Right
```
[jrhammon@esgmonster Stencil]$ ./stencil-coarray 10 300
Parallel Research Kernels version 2.16
CAF stencil execution on 2D grid
Number of images     =       36
Grid size            =      300
Radius of stencil    =        2
Type of stencil      = star
Data type            = double precision
Compact representation of stencil loop body
Untiled
Number of iterations =       10
Solution validates
Rate (MFlops/s):    133.669145 Avg time (s):      0.012454
```

# Wrong
```
[jrhammon@esgmonster Stencil]$ ./stencil-coarray 10 400
Parallel Research Kernels version 2.16
CAF stencil execution on 2D grid
Number of images     =       36
Grid size            =      400
Radius of stencil    =        2
Type of stencil      = star
Data type            = double precision
Compact representation of stencil loop body
Untiled
Number of iterations =       10
ERROR: L1 norm =     21.557800 Reference L1 norm =     22.000000
Rate (MFlops/s):    216.659568 Avg time (s):      0.013752
```

@afanfa Did you ever see this with OpenCoarrays?  I don't test with that, and wonder if I need to investigate if this is an Intel compiler bug.

### PR DESCRIPTION
**Pull request by afanfa**
This patch fixes #97 and #98. Note that this code works only for STAR stencil without tiling.

### CODE REVIEW

**Comment by jeffhammond** [comment]
Thanks! I need to run tests manually since our Travis setup doesn't support multi-image coarrays testing yet (I think).

Rob: please don't merge until we have tested this thoroughly. 

I have found that tiling doesn't pay off consistently in the other Fortran Stencil implementations, so disabling tiling isn't a huge loss, at least temporarily.

I'm surprised the not-star stencil is not fixed by this, since the decomposition is just a function of radius. I will take a look at the code later.

**Comment by afanfa** [comment]
The code now supports also non-star stencil. It is wise to replace the "sync all" between the y and x halo exchange with "sync images".

**Comment by jeffhammond** [comment]
Can you rebase/merge the latest master, which now includes OpenCoarrays in the test harness?

**Comment by afanfa** [comment]
Done, apparently  all the checks have passed.

**Pull request merged**
