### PR TITLE
Travis OpenCoarrays

### PR DESCRIPTION
**Pull request by jeffhammond**

### CODE REVIEW

**Comment by zbeekman** [comment]
If you encounter any OpenCoarrays related issues I'd be happy to take a look, just ping me...

**Comment by jeffhammond** [comment]
The OpenCoarrays install works on Mac but not on Linux.  I am still debugging the Linux situation but for now I will merge, since the Linux tests are allowed to fail in Travis and will not affect the pass/fail status of the project.

**Comment by zbeekman** [comment]
Looks like an issue finding mpifort? https://travis-ci.org/ParRes/Kernels/jobs/134322874#L7211
I always use mpif90 but it shouldn't make a difference... There is a lot of complexity and output in those build scripts, so my quick, ad-hoc post-mortem might not be accurate.

**Comment by jeffhammond** [comment]
@zbeekman As you can see in https://github.com/jeffhammond/PRK/commit/61cf4644d3c8f588bae17d03f5463380b700dd94, I was being a moron.

**Comment by zbeekman** [comment]
happens to me all the time 😉 (and you're usually around to point it out, when it's on github 😆 )

**Pull request merged**
