### PR TITLE
Update PRK2 for new Grappa installation procedure

### PR DESCRIPTION
**Pull request by nelsonje**
@rfvander , here are my changes to support the new Grappa installation procedure.

Before building (with ```make allgrappa```), I sourced ```<Grappa installation directory>/bin/settings.sh``` and copied ```common/make.defs.in``` to ```common/make.defs```. Does that work for you too?

### CODE REVIEW

**Comment by rfvander** [comment]
This looks very good, Jacob. Let me give these changes a spin and I’ll get back to you. Thank you for all your efforts!

Rob

**Comment by rfvander** [comment]
Hi Jacob,

I just noticed one thing. If I don’t install Grappa (many people will skip one or more runtimes), there is a problem doing “make clean” in the top level directory:
cd GRAPPA/Synch_p2p;        make clean
make[1]: Entering directory `/home/rfvander/esg-prk-devel/GRAPPA/Synch_p2p'
../../common/GRAPPA.defs:2: /share/Grappa/grappa.mk: No such file or directory
make[1]: *** No rule to make target `/share/Grappa/grappa.mk'.  Stop.
make[1]: Leaving directory `/home/rfvander/esg-prk-devel/GRAPPA/Synch_p2p'
make: *** [clean] Error 2

Rob

**Comment by rfvander** [comment]
OK, this is how I am fixing this in GRAPPA.defs.

include ../../common/make.defs
ifneq ($(GRAPPATOP),)
include $(GRAPPATOP)/share/Grappa/grappa.mk
endif
CCOMPILER=$(GRAPPA_CXX)
CLINKER=$(GRAPPA_LD)
COMOBJS=
PROG_ENV=-DGRAPPA

From: Van Der Wijngaart, Rob F
Sent: Tuesday, June 16, 2015 9:09 AM
To: 'ParRes/Kernels'; ParRes/Kernels
Subject: RE: [Kernels] Update PRK2 for new Grappa installation procedure (#2)

Hi Jacob,

I just noticed one thing. If I don’t install Grappa (many people will skip one or more runtimes), there is a problem doing “make clean” in the top level directory:
cd GRAPPA/Synch_p2p;        make clean
make[1]: Entering directory `/home/rfvander/esg-prk-devel/GRAPPA/Synch_p2p'
../../common/GRAPPA.defs:2: /share/Grappa/grappa.mk: No such file or directory
make[1]: *** No rule to make target `/share/Grappa/grappa.mk'.  Stop.
make[1]: Leaving directory `/home/rfvander/esg-prk-devel/GRAPPA/Synch_p2p'
make: *** [clean] Error 2

Rob

**Comment by nelsonje** [comment]
Sounds good, Rob!

**Comment by nelsonje** [comment]
You want me to do that in this pull request so you can just merge it?

**Comment by rfvander** [comment]
Not necessary, Jacob. I did all the merges by hand, because our development repo has changed a lot in the meantime. Once we are ready to push that to the public repo, it will have your changes, plus all of ours as well.

Rob

**Comment by nelsonje** [comment]
Okay! Then I guess I'll close this pull request.

**Comment by rfvander** [comment]
Sure, thanks!

Rob

**Comment by rfvander** [comment]
Hi Jacob,

I pulled the latest Grappa repo and am not trying to configure on my group’s shared machine (different from the research and production clusters I used before). I stuffed the third party tar in the right location and defined MPI_CXX_COMPILER,  MPI_C_COMPILER, and CXX. Then this is what happened during configuration:
[rfvander@esgmonster grappa]$ ./configure --prefix=~/intel --no-downloads
./configure:55: nested *?+ in regexp: /clang++/
./configure:56: nested *?+ in regexp: /clang++/
./configure:64: syntax error, unexpected kNOT
  if not(opt.cc) && not(opt.cxx)
                       ^
./configure:66: syntax error, unexpected kEND, expecting $end

Could you look into that? Thanks!

Rob

**Comment by nelsonje** [comment]
Whoops---I forgot to fix that regexp in a previous checkin. If you pull the
latest version it should be good.

**Comment by rfvander** [comment]
OK, thanks!
Doing the fresh build on a new system will be a good installation debugging device ☺.
Rob

**Comment by rfvander** [comment]
One more left after update:
[rfvander@esgmonster grappa]$ ./configure --prefix=~/intel --no-downloads
./configure:64: syntax error, unexpected kNOT
  if not(opt.cc) && not(opt.cxx)
                       ^
./configure:66: syntax error, unexpected kEND, expecting $end
[rfvander@esgmonster grappa]$

**Comment by nelsonje** [comment]
I suspect this is a Ruby version problem. What does ```ruby --version``` say?

If it's < 1.9.3 you'll need to find a newer version or wait for me to rewrite the configure script in bash.

**Comment by rfvander** [comment]
[rfvander@esgmonster ~]$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
☹

**Comment by rfvander** [comment]
I’ll need to put this on the backburner for now, Jacob, until Jeff (maintainer of the system) returns from his travels (and then I’ll be no vacation for three weeks, so it’ll be some time in July). It looks like the problems are caused by the negation function. On workaround could be to define symbols for that instead of calling not(x).

Rob

From: Van Der Wijngaart, Rob F
Sent: Tuesday, June 16, 2015 12:33 PM
To: 'ParRes/Kernels'; ParRes/Kernels
Subject: RE: [Kernels] Update PRK2 for new Grappa installation procedure (#2)

[rfvander@esgmonster ~]$ ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
☹

**Comment by nelsonje** [comment]
This immediate problem can be fixed by replacing "not" with "!", but I believe there are other parts of that script that require >1.9.3. I've been meaning rewrite that script anyway to get rid of our hard Ruby dependence; if you won't need to run on this system for a while I'll add the task to my queue.

**Comment by rfvander** [comment]
I don't need to run on this system, Jacob, but we now consider it the baseline system from which we maintain the public PRK repo. We now have so many runtimes that we support that maintenance is becoming nontrivial. Anyway, I think we'll be OK for now.

**Comment by rfvander** [comment]
One disadvantage is, though, that I will not be able to test the new build structure until _much_ later.

**Comment by rfvander** [comment]
I got through configure by replacing not(x) with !x, but then make died in the following way, even though I inserted the third party download in the right location:
[rfvander@esgmonster Make+Release]$ make -j
Scanning dependencies of target third-party-gflags
Scanning dependencies of target graph500-generator
[  0%] Creating directories for 'third-party-gflags'
[  0%] [  2%] [  2%] [  5%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/graph_generator.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/make_graph.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/splittable_mrg.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/utils.c.o
[  8%] Performing download step (verify and extract) for 'third-party-gflags'
-- verifying file...
     file='/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
-- verifying file... warning: did not verify file - no URL_HASH specified?
-- extracting...
     src='/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
     dst='/home/rfvander/grappa/build/Make+Release/third-party/build/src/gflags-2.0'
CMake Error at /home/rfvander/grappa/build/Make+Release/third-party/build/stamps/gflags/extract-third-party-gflags.cmake:11 (message):
  error: file to extract does not exist:
  '/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
 
 
make[2]: *** [third-party/build/stamps/gflags/third-party-gflags-download] Error 1
make[1]: *** [third-party/CMakeFiles/third-party-gflags.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking C static library libgraph500-generator.a
[  8%] Built target graph500-generator
make: *** [all] Error 2

**Comment by nelsonje** [comment]
Well, the requirement is 1.9.3. Running with 1.8.7 may finish without
errors on the console, but I have no confidence it will actually generate a
correct build configuration.

**Comment by nelsonje** [comment]
The other option right now is to create a build directory and construct and run the cmake command line by hand inside it; it'll be something like this:
```
cmake /sampa/home/nelson/grappa-whatever -G"Unix Makefiles" -DNO_DOWNLOADS=true -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DBASE_C_COMPILER=gcc -DBASE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/asdf
```

Otherwise you could try installing a newer Ruby in your home directory or check back later this week; I may be able to get this rewritten in bash by then.

**Comment by rfvander** [comment]
Fair enough ☺.

**Comment by rfvander** [comment]
OK, I got the right version of ruby installed, but am still experiencing problems with make (I blew build away first before running configure again):
[rfvander@esgmonster grappa]$ ./configure --prefix=~/intel --no-downloads                                                                                
cmake /home/rfvander/grappa -G"Unix Makefiles" -DNO_DOWNLOADS=true -DCMAKE_C_COMPILER=mpigcc -DCMAKE_CXX_COMPILER=mpigxx -DBASE_C_COMPILER=mpigcc -DBASE_CXX_COMPILER=mpigxx -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=~/intel 
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /opt/intel/impi/5.0.2.044/intel64/bin/mpigcc
-- Check for working C compiler: /opt/intel/impi/5.0.2.044/intel64/bin/mpigcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/impi/5.0.2.044/intel64/bin/mpigxx
-- Check for working CXX compiler: /opt/intel/impi/5.0.2.044/intel64/bin/mpigxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found MPI_C: /opt/intel/impi/5.0.2.044/intel64/lib/libmpifort.so;/opt/intel/impi/5.0.2.044/intel64/lib/release_mt/libmpi.so;/opt/intel/impi/5.0.2.044/intel64/lib/libmpigi.a;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
-- Found MPI_CXX: /opt/intel/impi/5.0.2.044/intel64/lib/libmpicxx.so;/opt/intel/impi/5.0.2.044/intel64/lib/libmpifort.so;/opt/intel/impi/5.0.2.044/intel64/lib/release_mt/libmpi.so;/opt/intel/impi/5.0.2.044/intel64/lib/libmpigi.a;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so  
-- Boost found:  1.55.0 -- 
-- Expecting third-party dependence sources to be found in /home/rfvander/grappa/third-party/downloads.
-- Using {mpigcc,mpigxx} to build third-party dependencies (if needed).
     boost: /usr/local/include and /usr/local/lib
    gflags: <building>
      glog: <building>
-- The ASM compiler identification is GNU
-- Found assembler: /opt/intel/impi/5.0.2.044/intel64/bin/mpigcc
-- Found Doxygen: /usr/bin/doxygen (found version "1.6.1") 
CMake Warning at CMakeLists.txt:518 (message):
  Dynamic library found didn't have .so extension:
  /opt/intel/impi/5.0.2.044/intel64/lib/libmpigi.a
 
 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rfvander/grappa/build/Make+Release
-------------------------------------
created build/Make+Release; to build:
> cd build/Make+Release; make
(use make -j<numcores> to build in parallel)
-------------------------------------
[rfvander@esgmonster grappa]$ cd build/Make+Release/
[rfvander@esgmonster Make+Release]$ make -j
Scanning dependencies of target third-party-gflags
Scanning dependencies of target graph500-generator
[  0%] [  0%] [  0%] Creating directories for 'third-party-gflags'
[  2%] [  5%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/graph_generator.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/splittable_mrg.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/utils.c.o
Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/make_graph.c.o
[  8%] Performing download step (verify and extract) for 'third-party-gflags'
-- verifying file...
     file='/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
-- verifying file... warning: did not verify file - no URL_HASH specified?
-- extracting...
     src='/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
     dst='/home/rfvander/grappa/build/Make+Release/third-party/build/src/gflags-2.0'
CMake Error at /home/rfvander/grappa/build/Make+Release/third-party/build/stamps/gflags/extract-third-party-gflags.cmake:11 (message):
  error: file to extract does not exist:
  '/home/rfvander/grappa/third-party/downloads/gflags-2.0-no-svn-files.tar.gz'
 
 
make[2]: *** [third-party/build/stamps/gflags/third-party-gflags-download] Error 1
make[1]: *** [third-party/CMakeFiles/third-party-gflags.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking C static library libgraph500-generator.a
[  8%] Built target graph500-generator
make: *** [all] Error 2

**Comment by nelsonje** [comment]
Hmm. In reviewing the instructions, it looks we ask you to put the tar file in that directory and then untar it. Perhaps you didn't untar it?

It would be convenient to not have to untar as well as download. Maybe I'll make the --no-downloads flag take the tar file as an argument and do the untarring for you.

**Comment by rfvander** [comment]
Dang, my bad. Will untar now.

**Comment by rfvander** [comment]
OK, I got a lot further, but some issues remain. Maybe I have the wrong version of the compiler. Here is what I did after untarring the third party software.
\rm -rf build
./configure --prefix=~/intel --no-downloads
cd build/Make+Release/
make && make install
And the output of the make (tail end only) is:
 /usr/bin/install -c -m 644 libglog.pc '/home/rfvander/grappa/build/Make+Release/third-party/lib/pkgconfig'
[ 22%] Completed 'third-party-glog'
[ 22%] Built target third-party-glog
Scanning dependencies of target graph500-generator
[ 22%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/graph_generator.c.o
[ 25%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/make_graph.c.o
[ 25%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/splittable_mrg.c.o
[ 27%] Building C object third-party/graph500-generator/CMakeFiles/graph500-generator.dir/utils.c.o
Linking C static library libgraph500-generator.a
[ 27%] Built target graph500-generator
Scanning dependencies of target all-third-party
[ 27%] Built target all-third-party
Scanning dependencies of target Communicator
[ 27%] Building CXX object system/CMakeFiles/Communicator.dir/Communicator.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [system/CMakeFiles/Communicator.dir/Communicator.cpp.o] Error 1
make[1]: *** [system/CMakeFiles/Communicator.dir/all] Error 2
make: *** [all] Error 2

**Comment by rfvander** [comment]
Compiler: [rfvander@esgmonster Make+Release]$ mpigxx -v 
mpigxx for the Intel(R) MPI Library 5.0 Update 2 for Linux*
Copyright(C) 2003-2014, Intel Corporation.  All rights reserved.
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

**Comment by rfvander** [comment]
On my research cluster the compiler version is more recent:
[rfvander@bar1 ~]$  mpigxx -v
mpigxx for the Intel(R) MPI Library 5.0 Update 1 for Linux*
Copyright(C) 2003-2014, Intel Corporation.  All rights reserved.
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140624/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140624/obj-x86_64-redhat-linux/cloog-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140624 (Red Hat 4.8.3-1) (GCC)

**Comment by rfvander** [comment]
OK, I got the right version of ruby and gcc now and was able to make Grappa as well as my application, Synch_p2p/p2p
But when I try to run I get this error:
mpiexec.hydra -np 4 ./p2p
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./p2p)
./p2p: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./p2p)

Do you know how I can coax my system so the runtime can find the correct version of the library?

**Comment by rfvander** [comment]
OK, got that problem fixed on our system. Now I can run and the solution always verifies, but upon exiting there is an error. This is with the latest version of Grappa that I downloaded. I think we saw something like this before. it happens in the version of Synch_p2p that I sent to you. If I change the number of cores, the number of error messages changes by the same number.
[rfvander@esgmonster Synch_p2p]$ mpiexec.hydra -np 2 ./p2p 100 1000 100                                                     
I0617 09:10:12.643038 49736 Grappa.cpp:629] 
-------------------------
Shared memory breakdown:
  node total:                   62.8096 GB
  locale shared heap total:     31.4048 GB
  locale shared heap per core:  15.7024 GB
  communicator per core:        0.125 GB
  tasks per core:               0.0156631 GB
  global heap per core:         3.9256 GB
  aggregator per core:          0.00247955 GB
  shared_pool current per core: 4.76837e-07 GB
  shared_pool max per core:     3.9256 GB
  free per locale:              23.2673 GB
  free per core:                11.6337 GB
-------------------------
Grappa pipeline execution on 2D grid
Number of processes            = 2
Grid sizes                     = 1000x100
Number of iterations           = 100
Solution validates
Rate (MFlops/s): 887.799  Avg time (s): 0.0002228
Exiting due to signal 11 with siginfo 0x7fff43deb630 and payload 0x7fff43deb500
Exiting due to signal 11 with siginfo 0x7fff89e2ba70 and payload 0x7fff89e2b940

**Comment by rfvander** [comment]
Same thing with the Stencil code

**Pull request closed without merging**
