### PR TITLE
add threaded versions of transpose-ispc via OpenMP

### PR DESCRIPTION
**Pull request by jeffamstutz**
I used ISPC's tasking syntax to thread `transpose-ispc` using OpenMP as the tasking system...got nice results.

### CODE REVIEW

**Comment by jeffamstutz** [comment]
FYI: I think once a second kernel is ported to ISPC, then ISPC should get its own directory.

**Comment by jeffhammond** [comment]
@jeffamstutz I am fine with ISPC having it's own directory, although I keep CUDA and OpenCL in the C++ directory despite being language extensions.  Is this for PRK infrastructure reasons or language purity reasons?

**Comment by jeffamstutz** [comment]
I was thinking more about language purity. I suppose I was confused by OpenMP having both its own directory and being in `C1z` and `Cxx11`.

However, my opinion here isn't strong, so I'm good either way.

**Comment by jeffamstutz** [comment]
I would add more ISPC implementations in other PRs anyway, so this could be merged if it looks good to you.

**Comment by jeffhammond** [comment]
@jeffamstutz Unnecessary project history here.  Please ignore if you have something better to do 😄 

When I joined Intel, the PRK project was all C89 (with optional `restrict`) and every parallel model got its own directory (`SERIAL`, `OPENMP`, `MPI`).  Then we added UPC (derived from C99), Charm++ (roughly aligned with C++98), and Grappa (C++11?), but we kept the pattern of each parallel model having its own directory.

When I started porting to new languages in earnest, I decided to sort by the underlying language, because that made the build system and other infrastructure issues simpler.  I also preferred a shallow structure so I didn't have to create a lot of Makefiles, both for human efficiency and build parallelism ("recursive make considered harmful").

Anyways, ISPC clearly isn't ISO C so I'm happy for it to live separately, particularly if the code is not 1:1 with other C implementations.

**Comment by jeffamstutz** [comment]
Sounds good, I may divide them out sometime in the future, but will keep the current structure for now.

**Comment by jeffhammond** [comment]
I’ll refactor the directory when you’re done. It’s a minor change but thrashes git.

**Comment by jeffamstutz** [comment]
Works for me!

**Comment by jeffamstutz** [comment]
Also, FYI: I'm super comfortable with git, so you do what you want to do and I can adapt.

**Comment by jeffhammond** [comment]
In my experience, Git struggles with directory reorganization and I have dozens of unmerged branches I don’t want to thrash until necessary.

**Pull request merged**
