### PR TITLE
Shmem preprocessor portability

### PR DESCRIPTION
**Pull request by jeffhammond**
@jdinan @rfvander Please review and/or test this.

Yes, this contains the unrelated `.gitignore` commit.  Sorry.

### CODE REVIEW

**Comment by jdinan** [comment]
The problem with b04a7ce is that it addresses only part of the deprecation that occurred in OSH 1.2; the deprecated functions (shmalloc, shfree, ...) are not dealt with and there are no calls to shmem_finalize, so the code still relies on legacy shutdown.  At the same time _SHMEM constants are not removed from the spec and every SHMEM implementation supports them.  Unless you want to address the other OSH 1.2 issues, I would suggest to declare this OSH 1.1 compliant code and punt to see what the world looks like when you actually have to move on to a newer version of the spec.

**Comment by jeffhammond** [comment]
@jdinan Deprecated functions is a legitimate, but independent issue.  I will fix that next.  I do not understand why it must be addressed in this PR.

**Comment by jdinan** [comment]
Does #16 contain all of these patches?  If so, it would be helpful to close this PR and keep discussion in one place.

**Comment by jeffhammond** [comment]
Move to #16.

**Pull request closed without merging**
